name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      # Récupère le dernier commit et le passe comme variable d'environnement
      - name: Get latest commit message
        id: commit
        run: echo "LAST_COMMIT=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - run: chmod +x ./release.sh
      - run: ./release.sh standard-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LAST_COMMIT: ${{ env.LAST_COMMIT }}  # Passe le commit en variable d'environnement
